server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: iso8583-simulator

  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/La_Paz

  web:
    resources:
      static-locations: classpath:/static/web/
      cache-period: 3600

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configuración del simulador ISO8583
iso8583:
  simulator:
    switch:
      host: 172.16.1.211
      port: 5105
      timeout: 30000
      connection-pool:
        initial-size: 2
        max-size: 10
        max-idle-time: 300000
      retry:
        max-attempts: 3
        delay: 1000

    field-generation:
      auto-generate-missing: true
      trace-number:
        start: 1
        max: 999999
      datetime:
        auto-generate: true
        timezone: America/La_Paz

    message:
      default-packager: generic-packager.xml
      validate-before-send: true
      log-messages: true

    monitoring:
      enabled: true
      metrics-interval: 60000
      performance-tracking: true

# Logging
logging:
  level:
    com.iso8583.simulator: DEBUG
    org.jpos: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/iso8583-simulator.log
    max-size: 100MB
    max-history: 30

# Actuator para monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Documentación API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

---
# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev

iso8583:
  simulator:
    switch:
      host: localhost
      port: 8583
    message:
      log-messages: true
    monitoring:
      enabled: true

logging:
  level:
    com.iso8583.simulator: DEBUG

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: prod

iso8583:
  simulator:
    switch:
      host: 172.16.1.211
      port: 5105
    message:
      log-messages: false
    monitoring:
      enabled: true

logging:
  level:
    com.iso8583.simulator: INFO
    root: WARN

---
# Perfil de testing
spring:
  config:
    activate:
      on-profile: test

iso8583:
  simulator:
    switch:
      host: localhost
      port: 8583
    message:
      log-messages: true
    monitoring:
      enabled: false

logging:
  level:
    com.iso8583.simulator: DEBUG