server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: iso8583-simulator

  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/La_Paz

  web:
    resources:
      static-locations: classpath:/static/web/
      cache-period: 3600

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ================================
# CONFIGURACIÓN DEL SIMULADOR ISO8583 CON SOPORTE MOCK/REAL
# ================================
iso8583:
  simulator:
    # Modo de operación: mock, real, hybrid
    mode: ${SIMULATOR_MODE:mock}

    # Permitir cambio dinámico de modo en runtime
    dynamic-mode-change: true

    # Configuración del switch/autorizador (modo REAL)
    switch:
      host: ${AUTHORIZER_HOST:172.16.1.211}
      port: ${AUTHORIZER_PORT:5105}
      timeout: ${AUTHORIZER_TIMEOUT:30000}
      enabled: true

      connection-pool:
        initial-size: 2
        max-size: 10
        max-idle-time: 300000

      retry:
        max-attempts: 3
        delay: 1000

    # Configuración del modo MOCK
    mock:
      enabled: true
      min-response-time: 50
      max-response-time: 200
      success-rate: 0.95
      realistic-errors: true

    # Configuración de conexión
    connection:
      keep-alive-interval: 60000
      auto-reconnect: true
      max-reconnect-attempts: 5

    # Configuración de generación de campos
    field-generation:
      auto-generate-missing: true
      trace-number:
        start: 1
        max: 999999
      datetime:
        auto-generate: true
        timezone: America/La_Paz

    # Configuración de mensajes
    message:
      default-packager: generic-packager.xml
      validate-before-send: true
      log-messages: true

    # Configuración de monitoreo
    monitoring:
      enabled: true
      metrics-interval: 60000
      performance-tracking: true

# ================================
# CONFIGURACIÓN DEL STRATEGY PATTERN
# ================================

# Configuración de validaciones
validation:
  terminal-validation:
    iso8583-format-validation: true        # Estructura del mensaje
    field-length-validation: true          # Longitud de campos
    required-fields-validation: true       # Campos obligatorios
    character-set-validation: true         # Caracteres permitidos

  business-validation:
    pan-luhn-validation: false             # ❌ Lo hace el core
    amount-limits-validation: false        # ❌ Lo hace el core
    card-status-validation: false          # ❌ Lo hace el core

# Configuración de transacciones
transaction:
  strategy:
    enabled-types:
      - BALANCE_INQUIRY
      - CASH_ADVANCE
      - PURCHASE
      - TRANSFER
      - AUTHORIZATION
      - REVERSAL

    default-currency: "068"                # Bolivia
    default-country: "068"                 # Bolivia
    default-acquiring-institution: "409911"

    timeout-ms: 30000                      # 30 segundos
    retry-attempts: 2

# ================================
# LOGGING
# ================================
logging:
  level:
    com.iso8583.simulator: DEBUG
    com.iso8583.simulator.core.transaction: DEBUG
    com.iso8583.simulator.web.controller.TransactionController: INFO
    com.iso8583.simulator.web.service.TransactionService: INFO
    org.jpos: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{mode:-UNKNOWN}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{mode:-UNKNOWN}] %logger{36} - %msg%n"
  file:
    name: logs/iso8583-simulator.log
    max-size: 100MB
    max-history: 30

# ================================
# ACTUATOR Y DOCUMENTACIÓN
# ================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

---
# ================================
# PERFIL DE DESARROLLO
# ================================
spring:
  config:
    activate:
      on-profile: dev

iso8583:
  simulator:
    mode: mock  # Modo mock por defecto en desarrollo
    dynamic-mode-change: true

    switch:
      host: 172.16.1.211
      port: 5105
      timeout: 10000

    mock:
      enabled: true
      min-response-time: 30
      max-response-time: 100
      success-rate: 0.98

    message:
      log-messages: true

    monitoring:
      enabled: true

logging:
  level:
    com.iso8583.simulator: DEBUG
    org.springframework.web: DEBUG

---
# ================================
# PERFIL DE TESTING
# ================================
spring:
  config:
    activate:
      on-profile: test

validation:
  terminal-validation:
    iso8583-format-validation: true
    field-length-validation: false        # Permitir campos mal formateados
    required-fields-validation: false     # Permitir campos faltantes
  business-validation:
    pan-luhn-validation: false            # Permitir PANs inválidos
    amount-limits-validation: false       # Permitir montos negativos/enormes

transaction:
  strategy:
    timeout-ms: 10000                     # Timeout más corto para testing
    retry-attempts: 1

iso8583:
  simulator:
    mode: mock  # Solo mock en testing
    dynamic-mode-change: false  # No permitir cambios en testing

    switch:
      host: localhost
      port: 8583
      timeout: 5000

    mock:
      enabled: true
      min-response-time: 10
      max-response-time: 50
      success-rate: 1.0  # 100% éxito en tests

    message:
      log-messages: false  # Menos logs en testing
      validate-before-send: true

    monitoring:
      enabled: false

logging:
  level:
    com.iso8583.simulator: INFO
    org.springframework: WARN

---
# ================================
# PERFIL DE TESTING AVANZADO
# ================================
spring:
  config:
    activate:
      on-profile: testing

validation:
  terminal-validation:
    iso8583-format-validation: true
    field-length-validation: false        # Permitir campos mal formateados
    required-fields-validation: false     # Permitir campos faltantes
  business-validation:
    pan-luhn-validation: false            # Permitir PANs inválidos
    amount-limits-validation: false       # Permitir montos negativos/enormes

transaction:
  strategy:
    timeout-ms: 10000                     # Timeout más corto para testing
    retry-attempts: 1

---
# ================================
# PERFIL DE PRODUCCIÓN
# ================================
spring:
  config:
    activate:
      on-profile: prod

iso8583:
  simulator:
    mode: real  # Modo real por defecto en producción
    dynamic-mode-change: true  # Permitir cambio para mantenimiento

    switch:
      host: 172.16.1.211
      port: 5105
      timeout: 30000
      connection-pool:
        initial-size: 5
        max-size: 20
        max-idle-time: 600000

    mock:
      enabled: true  # Mantener disponible para pruebas
      min-response-time: 80
      max-response-time: 300
      success-rate: 0.95

    message:
      log-messages: false  # Menos logging en producción
      validate-before-send: true

    monitoring:
      enabled: true
      metrics-interval: 30000  # Métricas más frecuentes

logging:
  level:
    com.iso8583.simulator: INFO
    org.jpos: WARN
    org.springframework: WARN
    root: WARN

---
# ================================
# PERFIL DE DEMOSTRACIÓN
# ================================
spring:
  config:
    activate:
      on-profile: demo

iso8583:
  simulator:
    mode: hybrid  # Modo híbrido para demos
    dynamic-mode-change: true

    switch:
      host: demo.authorizer.com
      port: 8583
      timeout: 15000

    mock:
      enabled: true
      min-response-time: 100
      max-response-time: 500
      success-rate: 0.90  # Algunos errores para mostrar manejo
      realistic-errors: true

    message:
      log-messages: true

    monitoring:
      enabled: true